{"uuid": "6d11c97b-269c-4d00-9add-253456ed3281", "children": ["fa19e868-616f-4e38-8dd7-73964a6654f9", "ce976aa3-4aed-4839-8c40-710a01fc37cc"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up\n\n", "trace": "  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python\\Automation\\AppiumFramework\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.getDriverMethod()\n  File \"D:\\Python\\Automation\\AppiumFramework\\base\\DriverClass.py\", line 18, in getDriverMethod\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    super().__init__(\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1644153567769, "stop": 1644153589872}], "start": 1644153567769, "stop": 1644153590037}