{"uuid": "2b5b4a1f-cda7-470d-836c-aa79a98d58a4", "children": ["cfe1f346-d9b0-4823-a71e-f338ab123981", "2ec02e34-75be-48bd-9c4d-1460fe328bcf", "28b52259-786a-4491-ab00-3c4c56bd856c"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))\n", "trace": "  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Python\\Automation\\AppiumFramework\\tests\\conftest.py\", line 10, in beforeClass\n    driver = driver1.getDriverMethod()\n  File \"D:\\Python\\Automation\\AppiumFramework\\base\\DriverClass.py\", line 18, in getDriverMethod\n    driver = webdriver.Remote(\"http://127.0.0.1:4723/wd/hub\", desired_caps)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 151, in __init__\n    super().__init__(\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 157, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\appium\\webdriver\\webdriver.py\", line 225, in start_session\n    response = self.execute(RemoteCommand.NEW_SESSION, parameters)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 319, in execute\n    response = self.command_executor.execute(driver_command, params)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 374, in execute\n    return self._request(command_info[0], url, body=data)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\selenium\\webdriver\\remote\\remote_connection.py\", line 397, in _request\n    resp = self._conn.request(method, url, body=body, headers=headers)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\request.py\", line 70, in request\n    return self.request_encode_body(method, url, fields=fields,\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\request.py\", line 150, in request_encode_body\n    return self.urlopen(method, url, **extra_kw)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\poolmanager.py\", line 324, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\connectionpool.py\", line 637, in urlopen\n    retries = retries.increment(method, url, error=e, _pool=self,\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\util\\retry.py\", line 368, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\packages\\six.py\", line 685, in reraise\n    raise value.with_traceback(tb)\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\connectionpool.py\", line 597, in urlopen\n    httplib_response = self._make_request(conn, method, url,\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\connectionpool.py\", line 384, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 2, in raise_from\n  File \"C:\\Users\\a.padlo\\AppData\\Roaming\\Python\\Python39\\site-packages\\urllib3\\connectionpool.py\", line 380, in _make_request\n    httplib_response = conn.getresponse()\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\http\\client.py\", line 1345, in getresponse\n    response.begin()\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\http\\client.py\", line 307, in begin\n    version, status, reason = self._read_status()\n  File \"c:\\users\\a.padlo\\appdata\\local\\programs\\python\\python39\\lib\\http\\client.py\", line 276, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\n"}, "start": 1644171339783, "stop": 1644171380876}], "start": 1644171339783, "stop": 1644171381839}